name: Upterm SSH Debug Session

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Start Upterm SSH Session
        uses: owenthereal/action-upterm@v1
        with:
          limit-access-to-actor: true
